# CloudClusters.jl's default configuration

[defaults]

user = "ubuntu"
sshflags = "" 
exename = "/home/ubuntu/.juliaup/bin/julia"
directory = "/home/ubuntu"
exeflags = "--optimize=3"
tunneled = true
threadlevel = "multiple"
mpiflags = "--map-by node --hostfile /home/ubuntu/hostfile"

[local]

directory = "."
mpiflags = ""

[ec2]

imageid = "ami-09121cfdb459a0804"  # found at us-east-1 (North Virginia). To use in other regions, copy it.

# placement_group = "pg-XXXXXXXXXXXX" or "automatic"
# security_group_id = "sg-XXXXXXXXXXXX" or "automatic"
# subnet_id = "subnet-XXXXXXXXXXXX"

[gcp]