# CloudClusters.jl's default configuration

[defaults]

user = "ubuntu"
sshflags = "" 
exename = "/home/ubuntu/.juliaup/bin/julia"
directory = "/home/ubuntu"
exeflags = "--optimize=3"
tunneled = true
threadlevel = "multiple"
mpiflags = "--map-by node --hostfile /home/ubuntu/hostfile"

[local]

directory = "."
mpiflags = ""

[ec2]

imageid = "ami-0bec2868f8f28086f"  # found at us-east-1 (North Virginia). To use in other regions, copy it.
#security_group_id = "sg-09e2e7c3eebd45160"

# placement_group = "pg-XXXXXXXXXXXX" or "automatic"
# security_group_id = "sg-XXXXXXXXXXXX" or "automatic"
# subnet_id = "subnet-XXXXXXXXXXXX"

[gcp]

imageid = "hpc-shelf-311900/global/images/cloudclusters-basic-v5"
zone = "us-central1-a"
project = "hpc-shelf-311900"
user = "heron"
exename = "/home/heron/.juliaup/bin/julia"
directory = "/home/heron"
mpiflags = "--map-by node --hostfile /home/heron/hostfile"
# network_interface = "default"
