
[defaults]

user = "ubuntu"
keyname = "hpc-shelf-credential"
sshflags = "-i /home/heron/hpc-shelf-credential.pem" 
exename = "/home/ubuntu/.juliaup/bin/julia"
directory = "/home/ubuntu/heron/NPBApps.jl"
exeflags = ""
tunneled = true
threadlevel = "multiple"
mpiflags = "--map-by node --hostfile /home/ubuntu/hostfile"
