
[defaults]

user = "ubuntu"
sshflags = "" 
exename = "/home/ubuntu/.juliaup/bin/julia"
directory = "/home/ubuntu"
exeflags = "--optimize=3"
tunneled = true
threadlevel = "multiple"
mpiflags = "--map-by node --hostfile /home/ubuntu/hostfile"

[local]

directory = "."
mpiflags = ""

[ec2]

imageid = "ami-0ce455c31c5fec661"
#placement_group = "automatic"
security_group_id = "sg-039de945285a31f89"
subnet_id = "subnet-3fca5558"

[gcp]