name = "CloudClusters"
uuid = "4ca6f12b-c8f1-4945-b50f-6bb73234c039"
authors = ["Francisco Heron de Carvalho Junior <heron@dc.ufc.br> e João Marcelo Uchôa de Alencar <joao.marcelo@ufc.br>"]
version = "0.1.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Random = "1.11.0"
