# Este é o arquivo que o script pcluster recebe para criar um cluster.
Region: us-east-1
Image:
  Os: ubuntu2204
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-a91a21f4
  Ssh:
    KeyName: pcluster
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      Instances:
      - InstanceType: t2.micro
      MinCount: 4
      MaxCount: 4
    Networking:
      SubnetIds:
      - subnet-a91a21f4
